server:
    port: 3000

amazon:
    dynamodb:
        endpoint: http://localhost:8000/
    aws:
        accesskey: key
        secretkey: key2
        region: AP_SOUTHEAST_2
spring:        
    security:
        user:
            name: demo
            password: demo
springdoc:
    swagger-ui:
        csrf:
            enabled: false            
