package com.hjdrsa.dynamodb.poc.event;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEpochDate;
import com.fasterxml.jackson.annotation.JsonView;
import com.hjdrsa.dynamodb.poc.config.View;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * @author hjd
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Event")
public class Event {
  
  @JsonView({ View.Add.class, View.List.class })
  @DynamoDBHashKey
  private String userId;
  
  @JsonView({ View.List.class, View.Add.class, View.One.class })
  @DynamoDBRangeKey
  @DynamoDBAutoGeneratedKey
  private String id;
  
  @JsonView({ View.Add.class, View.List.class, View.One.class })
  @DynamoDBAttribute
  private String name;
  
  @JsonView({ View.Add.class, View.List.class, View.One.class })
  @DynamoDBAttribute
  @DynamoDBTypeConvertedEpochDate
  private Date date;
}
